[package]
name = "justly"
description = "Justly - Decentralized dispute resolution protocol with commit-reveal voting"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false
version.workspace = true

[package.metadata.stellar]
cargo_inherit = true

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
soroban-sdk = { version = "23.1.0", default-features = false, features = ["alloc"] }
stellar-registry = "0.0.5"
sha2 = { version = "0.10", default-features = false }

[dev-dependencies]
stellar-xdr = { version = "24.0.0", features = ["curr", "serde"] }
soroban-sdk = { version = "23.1.0", features = ["testutils"] }
